spring:
  datasource:
    password: newPassword.1
    url: jdbc:mysql://localhost:3306/usermanager
    username: newuser
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true